language: java
jdk:
- oraclejdk8
before_install:
- export | grep SAUCE_
script: make run_all_in_parallel
env:
  global:
  - BUILD_TAG=$TRAVIS_REPO_SLUG+$TRAVIS_BUILD_NUMBER
  - SAUCE_USERNAME=sauce_examples
addons:
  jwt:
    secure: CRQ8sPcrBCWuWRSEXBcwljL2N/YGVsXojLTWGH9g7pfKcWGTRklLYdEi7blyvnNJoIS43AjiG1BZ+aQDMLkBFgRBCfZHeoftMEqO7hHrWXctHLQQWEphoSkH6++mbiq3hxO2GgH0Ix5T2W+bHOjoCXv7/XEHKUkgd/jmLM68uOrvdVrZQbOV9Uy5uStkVcLjYb58b5cmagIJUjf9QKC1lKns2WbelaqM2Jpw9sJlLN24uhDtXfzKmKWUPDgteYfwWg/xifOwEVLCDSTicA3gV6dXgTbnfDoFVZGZyoIvj+YEB8OBejwnbO0XXfextnD4BMfu2t133eR/bGHMNIxt6V+/soGKV+cj0vwXI59Jbl9FoYQc2CpyEOWE9Xoecj0GxXd9p2U6S8SMs95y0zvF1xYFWhKKC1LQwHmSMeTCvXQmnzqYjM2YGlrisvMHx6t2DH3+5XhbwcdvtoJSZZmdA04l0tWC1dVv61uL2AAR3HfWEjIinFJQvpiUsT9068NH1216AhA4Fym8yatIbZnEDl1+Z/osOoMWw1GBOJG9msMvbva3GyDwehrB6MN0zdiK0T/pCM+nunlHsdFmjdkpnZhUPL2oKluSzu4pg3hz8d56NfcfaJP+TYeQUo7aPWvebdKRmASr/4xiXWh3UIrINKisTpRTQ/CnaJQM+oQs1xE=
